#!/bin/bash
# setup.sh - Sets up the development environment for TDD Skill Builder
# This script ensures bashunit and other tools are available

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TOOLS_DIR="${PROJECT_ROOT}/tools"
BASHUNIT_VERSION="latest"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Check if a command is available
command_exists() {
  command -v "$1" &>/dev/null
}

# Install bashunit to project tools directory
install_bashunit() {
  log_info "Installing bashunit to ${TOOLS_DIR}..."

  mkdir -p "${TOOLS_DIR}"

  if command_exists curl; then
    curl -L -o "${TOOLS_DIR}/bashunit" \
      "https://github.com/TypedDevs/bashunit/releases/download/${BASHUNIT_VERSION}/bashunit" 2>/dev/null
  elif command_exists wget; then
    wget -O "${TOOLS_DIR}/bashunit" \
      "https://github.com/TypedDevs/bashunit/releases/download/${BASHUNIT_VERSION}/bashunit" 2>/dev/null
  else
    log_error "Neither curl nor wget found. Cannot download bashunit."
    return 1
  fi

  chmod +x "${TOOLS_DIR}/bashunit"
  log_info "bashunit installed successfully"
}

# Get bashunit path (project-local or global)
get_bashunit_path() {
  if [[ -x "${TOOLS_DIR}/bashunit" ]]; then
    echo "${TOOLS_DIR}/bashunit"
  elif command_exists bashunit; then
    command -v bashunit
  else
    echo ""
  fi
}

# Main setup function
setup() {
  log_info "Setting up TDD Skill Builder development environment..."
  echo ""

  # Check required system tools
  local missing_tools=()

  if ! command_exists shellcheck; then
    missing_tools+=("shellcheck")
  else
    log_info "shellcheck: $(command -v shellcheck)"
  fi

  if ! command_exists shfmt; then
    missing_tools+=("shfmt")
  else
    log_info "shfmt: $(command -v shfmt)"
  fi

  # Handle bashunit specially - prefer project-local installation
  local bashunit_path
  bashunit_path=$(get_bashunit_path)

  if [[ -z "$bashunit_path" ]]; then
    log_warn "bashunit not found. Installing..."
    install_bashunit
    bashunit_path=$(get_bashunit_path)
  fi

  if [[ -n "$bashunit_path" ]]; then
    log_info "bashunit: ${bashunit_path}"
  else
    missing_tools+=("bashunit")
  fi

  echo ""

  # Report missing tools
  if [[ ${#missing_tools[@]} -gt 0 ]]; then
    log_error "Missing tools: ${missing_tools[*]}"
    echo ""
    echo "Install missing tools:"
    for tool in "${missing_tools[@]}"; do
      case "$tool" in
        shellcheck)
          echo "  shellcheck: sudo apt install shellcheck (or brew install shellcheck)"
          ;;
        shfmt)
          echo "  shfmt:      sudo apt install shfmt (or brew install shfmt)"
          ;;
        bashunit)
          echo "  bashunit:   Run this script again or download manually"
          ;;
      esac
    done
    return 1
  fi

  log_info "All tools available!"
  echo ""

  # Create .env file with tool paths for other scripts
  cat >"${PROJECT_ROOT}/.env" <<EOF
# Auto-generated by setup.sh - tool paths for TDD Skill Builder
BASHUNIT_PATH="${bashunit_path}"
SHELLCHECK_PATH="$(command -v shellcheck)"
SHFMT_PATH="$(command -v shfmt)"
EOF
  log_info "Created .env file with tool paths"

  echo ""
  log_info "Setup complete! Run tests with:"
  echo "  ${bashunit_path} .claude/skills/tdd-skill-builder/tests/"
}

# Run setup if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup
fi
